# @package _global_

precision: 'bf16'

model:
  name: 'google/t5-v1_1-base'
  compile: true

optim:
  batch_size: 128
  total_steps: 65536
  grad_acc: 1

logging:
  every_steps: 2
  grad_l2: false
  weights_l2: false